/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as TradesRouteImport } from './routes/trades'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ApiCoinsRouteImport } from './routes/api/coins'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CoinIdRouteImport } from './routes/coin.$id'
import { Route as ApiCoinIdRouteImport } from './routes/api/coin.$id'
import { Route as ApiPublicHooksCheckAlertsRouteImport } from './routes/api/public/hooks/check-alerts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const TradesRoute = TradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoinsRoute = ApiCoinsRouteImport.update({
  id: '/api/coins',
  path: '/api/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CoinIdRoute = CoinIdRouteImport.update({
  id: '/coin/$id',
  path: '/coin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoinIdRoute = ApiCoinIdRouteImport.update({
  id: '/api/coin/$id',
  path: '/api/coin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCheckAlertsRoute =
  ApiPublicHooksCheckAlertsRouteImport.update({
    id: '/api/public/hooks/check-alerts',
    path: '/api/public/hooks/check-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/coins': typeof ApiCoinsRoute
  '/api/news': typeof ApiNewsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/coin/$id': typeof CoinIdRoute
  '/api/coin/$id': typeof ApiCoinIdRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/coins': typeof ApiCoinsRoute
  '/api/news': typeof ApiNewsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/coin/$id': typeof CoinIdRoute
  '/api/coin/$id': typeof ApiCoinIdRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/trades': typeof TradesRoute
  '/watchlist': typeof WatchlistRoute
  '/api/coins': typeof ApiCoinsRoute
  '/api/news': typeof ApiNewsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/coin/$id': typeof CoinIdRoute
  '/api/coin/$id': typeof ApiCoinIdRoute
  '/api/public/hooks/check-alerts': typeof ApiPublicHooksCheckAlertsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/auth'
    | '/blog'
    | '/news'
    | '/portfolio'
    | '/trades'
    | '/watchlist'
    | '/api/coins'
    | '/api/news'
    | '/blog/$slug'
    | '/coin/$id'
    | '/api/coin/$id'
    | '/api/public/hooks/check-alerts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/auth'
    | '/blog'
    | '/news'
    | '/portfolio'
    | '/trades'
    | '/watchlist'
    | '/api/coins'
    | '/api/news'
    | '/blog/$slug'
    | '/coin/$id'
    | '/api/coin/$id'
    | '/api/public/hooks/check-alerts'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/auth'
    | '/blog'
    | '/news'
    | '/portfolio'
    | '/trades'
    | '/watchlist'
    | '/api/coins'
    | '/api/news'
    | '/blog/$slug'
    | '/coin/$id'
    | '/api/coin/$id'
    | '/api/public/hooks/check-alerts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  NewsRoute: typeof NewsRoute
  PortfolioRoute: typeof PortfolioRoute
  TradesRoute: typeof TradesRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiCoinsRoute: typeof ApiCoinsRoute
  ApiNewsRoute: typeof ApiNewsRoute
  CoinIdRoute: typeof CoinIdRoute
  ApiCoinIdRoute: typeof ApiCoinIdRoute
  ApiPublicHooksCheckAlertsRoute: typeof ApiPublicHooksCheckAlertsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trades': {
      id: '/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coins': {
      id: '/api/coins'
      path: '/api/coins'
      fullPath: '/api/coins'
      preLoaderRoute: typeof ApiCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/coin/$id': {
      id: '/coin/$id'
      path: '/coin/$id'
      fullPath: '/coin/$id'
      preLoaderRoute: typeof CoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coin/$id': {
      id: '/api/coin/$id'
      path: '/api/coin/$id'
      fullPath: '/api/coin/$id'
      preLoaderRoute: typeof ApiCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/check-alerts': {
      id: '/api/public/hooks/check-alerts'
      path: '/api/public/hooks/check-alerts'
      fullPath: '/api/public/hooks/check-alerts'
      preLoaderRoute: typeof ApiPublicHooksCheckAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  NewsRoute: NewsRoute,
  PortfolioRoute: PortfolioRoute,
  TradesRoute: TradesRoute,
  WatchlistRoute: WatchlistRoute,
  ApiCoinsRoute: ApiCoinsRoute,
  ApiNewsRoute: ApiNewsRoute,
  CoinIdRoute: CoinIdRoute,
  ApiCoinIdRoute: ApiCoinIdRoute,
  ApiPublicHooksCheckAlertsRoute: ApiPublicHooksCheckAlertsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
