/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as ApiCoinsRouteImport } from './routes/api/coins'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as CoinIdRouteImport } from './routes/coin.$id'
import { Route as ApiCoinIdRouteImport } from './routes/api/coin.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoinsRoute = ApiCoinsRouteImport.update({
  id: '/api/coins',
  path: '/api/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinIdRoute = CoinIdRouteImport.update({
  id: '/coin/$id',
  path: '/coin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoinIdRoute = ApiCoinIdRouteImport.update({
  id: '/api/coin/$id',
  path: '/api/coin/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/watchlist': typeof WatchlistRoute
  '/api/coins': typeof ApiCoinsRoute
  '/api/news': typeof ApiNewsRoute
  '/coin/$id': typeof CoinIdRoute
  '/api/coin/$id': typeof ApiCoinIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/watchlist': typeof WatchlistRoute
  '/api/coins': typeof ApiCoinsRoute
  '/api/news': typeof ApiNewsRoute
  '/coin/$id': typeof CoinIdRoute
  '/api/coin/$id': typeof ApiCoinIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/news': typeof NewsRoute
  '/portfolio': typeof PortfolioRoute
  '/watchlist': typeof WatchlistRoute
  '/api/coins': typeof ApiCoinsRoute
  '/api/news': typeof ApiNewsRoute
  '/coin/$id': typeof CoinIdRoute
  '/api/coin/$id': typeof ApiCoinIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/news'
    | '/portfolio'
    | '/watchlist'
    | '/api/coins'
    | '/api/news'
    | '/coin/$id'
    | '/api/coin/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/news'
    | '/portfolio'
    | '/watchlist'
    | '/api/coins'
    | '/api/news'
    | '/coin/$id'
    | '/api/coin/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/news'
    | '/portfolio'
    | '/watchlist'
    | '/api/coins'
    | '/api/news'
    | '/coin/$id'
    | '/api/coin/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  NewsRoute: typeof NewsRoute
  PortfolioRoute: typeof PortfolioRoute
  WatchlistRoute: typeof WatchlistRoute
  ApiCoinsRoute: typeof ApiCoinsRoute
  ApiNewsRoute: typeof ApiNewsRoute
  CoinIdRoute: typeof CoinIdRoute
  ApiCoinIdRoute: typeof ApiCoinIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coins': {
      id: '/api/coins'
      path: '/api/coins'
      fullPath: '/api/coins'
      preLoaderRoute: typeof ApiCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin/$id': {
      id: '/coin/$id'
      path: '/coin/$id'
      fullPath: '/coin/$id'
      preLoaderRoute: typeof CoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coin/$id': {
      id: '/api/coin/$id'
      path: '/api/coin/$id'
      fullPath: '/api/coin/$id'
      preLoaderRoute: typeof ApiCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  NewsRoute: NewsRoute,
  PortfolioRoute: PortfolioRoute,
  WatchlistRoute: WatchlistRoute,
  ApiCoinsRoute: ApiCoinsRoute,
  ApiNewsRoute: ApiNewsRoute,
  CoinIdRoute: CoinIdRoute,
  ApiCoinIdRoute: ApiCoinIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
